### ISSUE TITLE
Quasar compatibility issue?

### ISSUE THREAD

**Issue by eric-nicular** [devbaji/vue3-google-login#15]
Is this project compatible with the Quasar framework? I got it working on a vanilla Vue3 project, but the login button won't appear in my Quasar app after following the instructions included in the Getting Started guide.

**Comment by eric-nicular** [comment]
I managed to get it working, but am curious as to the best way to console log a user's first and last name after retrieving it upon sign in?

**Comment by yobaji** [comment]
@eric-nicular can you share the code snippet?

**Comment by eric-nicular** [comment]
@yobaji I got it working. :) Thank you for replying!
However, I am curious about the recommended way to implement a logout button with this custom component?
Is there a section related to this in the docs?

**Comment by devbaji** [comment]
You cannot logout from the google session from your website https://github.com/devbaji/vue3-google-login/issues/3, can you test again if this issue still exists in iPhone? I tested this in my simulator, but can't replicate this issue.
