### ISSUE TITLE
Prompt not displaying in Chrome or Edge when not logged in to google or in incognito mode / private window.

### ISSUE THREAD

**Issue by jon-myers** [devbaji/vue3-google-login#17]
I am using the `googleOneTap({ autoLogin: false })` function upon mounting my app to trigger the login prompt. If I am browsing in a private window in firefox or safari, this appears:

<img width="399" alt="Screen Shot 2022-10-19 at 2 28 21 PM" src="https://user-images.githubusercontent.com/6957461/196775076-3d6afccb-c032-49d0-96bc-688637ade4c7.png">

In chrome and edge, nothing appears, and an error message is sent to the console:
`Prompt was not displayed, reason for not displaying: opt_out_or_no_session`

How can I ensure that this prompt window appears in chrome and edge when there is no currently active google session?

**Comment by devbaji** [comment]
This might be happening due to Exponential cooldown

[See here](https://developers.google.com/identity/gsi/web/guides/features#exponential_cooldown)
