### ISSUE TITLE
How to refresh the access token?

### ISSUE THREAD

**Issue by pweimann** [devbaji/vue3-google-login#22]
Hello,

I am using your vue3-google-login library in my project and I need to refresh the access token by calling the method requestAccessToken(). However, I am unsure of how to properly invoke this method.

Could you please provide some guidance on how to use the requestAccessToken() method for refreshing the access token? It would be really helpful if you could provide some sample code or step-by-step instructions.

Thank you for your time and assistance!

**Comment by devbaji** [comment]
This plugin is just a wrapper over [Google 3P Authorization JavaScript Library](https://developers.google.com/identity/oauth2/web/guides/load-3p-authorization-library). This should be only used to authenticate a valid google user and get the user info, other logics like you website user session/accetoken logics must be handled from your side.
