### ISSUE TITLE
Using slot to have a custom button changes the flow

### ISSUE THREAD

**Issue by Frement** [devbaji/vue3-google-login#25]
Customizing the button with any content changes the default flow. Callback doesn't get credential returned, instead it gets code, scope, authuser, hd and prompt.

Also it is requesting extra scopes email and profile.

This only happens when using the components slot.

**Comment by bfreskura** [comment]
You must handle this differently according to docs: https://yobaji.github.io/vue3-google-login/#custom-login-button

> ❗ For custom buttons this plugin use google.accounts.oauth2.initCodeClient and google.accounts.oauth2.initTokenClient under the hoods which gives [OAuth2 authorization code](https://developers.google.com/identity/oauth2/web/guides/use-code-model#auth_code_handling) and [Access Token](https://developers.google.com/identity/oauth2/web/guides/use-token-model) respectively in the callback response, but Google rendered login button and One Tap prompt gives a [CredentialResponse](https://developers.google.com/identity/gsi/web/reference/js-reference#CredentialResponse) with a JWT credential field, so if you are using a combination of these, validating your callback response on server-side can be a little tricky, this is more explained [here](https://yobaji.github.io/vue3-google-login/#server-side-validation)

**Comment by fahmi-nugroho** [comment]
so what must i do when i use custom template but want credential key to be send, little bit confuse here
