### ISSUE TITLE
Passing `prompt` to `GoogleLogin` did not show as OneTap

### ISSUE THREAD

**Issue by james10424** [devbaji/vue3-google-login#27]
According to the [doc](https://yobaji.github.io/vue3-google-login/#one-tap-prompt), the snippet below will show a OneTap prompt:
```
<GoogleLogin :callback="callback" prompt/>
```

But that still shows the regular sign in button.

**Comment by yobaji** [comment]
@james10424 Can you confirm you didnt see the prompt at all? Once closed manually it will get suppressed 
![image](https://user-images.githubusercontent.com/57234359/230345221-38e62b87-80db-4f86-b14b-4776f33f8419.png)
Check [here](https://developers.google.com/identity/gsi/web/guides/features#exponential_cooldown) for more info

**Comment by devbaji** [comment]
@james10424 Not sure if it is possible to customize the UI inside one tap prompt, [see this one](https://stackoverflow.com/questions/67467417/is-there-a-way-to-customize-the-text-content-of-google-one-tap-prompt)
