### ISSUE TITLE
doesn't work in Chrome Extensions

### ISSUE THREAD

**Issue by cleric1501** [devbaji/vue3-google-login#32]
the problem arises because due to Manifest V3 in Chrome extensions all external scripts are blocked by Google. 

Is it possible to compile js library internally ?

**Comment by MiladRST** [comment]
@cleric1501 Have you found out what to do in order to solve the problem ?? I've faced the same issue.

**Comment by devbaji** [comment]
@cleric1501 @MiladRST  Sorry for the late reply, is the problem still existing? Please reopen if this is still an issue!
