### ISSUE TITLE
CDN versions fail

### ISSUE THREAD

**Issue by ItsRainingHP** [devbaji/vue3-google-login#37]
The CDN version of this lib on jsdelivr fails with exports not defined.

![image](https://github.com/yobaji/vue3-google-login/assets/79205731/103625f9-566e-4e6e-9f21-ab7d05ba1c89)
![image](https://github.com/yobaji/vue3-google-login/assets/79205731/7894bbec-bd5b-4489-b4eb-39f08e7d8691)

Also, although few people seem to do it. It would be very appreciated if you added a CDN example.

**Comment by devbaji** [comment]
Hi @ItsRainingHP sorry for the really late fix 😐 
Added the [fix](https://github.com/devbaji/vue3-google-login/commit/51471e1896c56950b0cba9279f0a649dc095c43c) in v2.0.30
Using https://cdn.jsdelivr.net/npm/vue3-google-login@2.0.30/dist/index.umd.min.js will expose a variable `Vue3GoogleLogin` into window, which can be used to access some of the utility functions, might add a detailed example in docs page
