### ISSUE TITLE
Changing Google acc during login isn't reflected on the default login button

### ISSUE THREAD

**Issue by Dagge11** [devbaji/vue3-google-login#39]
After I try to log in with a different Google acc, new acc data is received but the name on the default button remains of the old account. The only way to change that name on the button is to logout from my Google acc completely in the browser. Pls fix that

Second, once I have been logged in with the Google account on my site I cannot log out to stay that way. Only way is to log out from my Google account in the browser which I don't like. There are many sites that allow logging out from Google account only on their site, not across the browser. How to do it? Thanks

**Comment by devbaji** [comment]
@Dagge11 The default button is an iframe which is loaded by google itself, the plugin doesnt have any control over the contents shown inside the iframe button, also there is no way a website can logout the google session https://github.com/devbaji/vue3-google-login/issues/3, the websites logout functionality should be implemented by the website developers.
