### ISSUE TITLE
I Got Cross-Origin-Opener-Policy Error But the popup is shown

### ISSUE THREAD

**Issue by pine630** [devbaji/vue3-google-login#40]
<img width="701" alt="image" src="https://github.com/yobaji/vue3-google-login/assets/41494676/ab3fd866-c89c-4c38-8929-712834a180c2">

I setup my application as the mannual and also the google cloud

<img width="482" alt="image" src="https://github.com/yobaji/vue3-google-login/assets/41494676/5d778f78-5aeb-4a18-a9cb-4f9c65203db4">

Could anyone help me about this error message?

**Comment by pjkostrzewski** [comment]
I've got the same:
![image](https://github.com/yobaji/vue3-google-login/assets/36046615/f931378a-7c71-43ce-b107-87cda67adebe)

**Comment by Wasabiiiiiii** [comment]
Same issue

**Comment by yobaji** [comment]
@Wasabiiiiiii @pjkostrzewski  @pine630  Can any of you guys share your code? I just tried an I am not getting any CORS errors

**Comment by joseperu2503** [comment]
Same issue :(

**Comment by Wasabiiiiiii** [comment]
For all those who are experiencing the error, I realized that my deployment of the static app ( in my case on azure ) was not correct, so in the staticwebapp.config.json file I configured the headers like this 

```
"globalHeaders": {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "POST, GET, OPTIONS",
        ""Cross-Origin-Opener-Policy": "same-origin-allow-popups"",
        "referrer-policy": "strict-origin-when-cross-origin"
    }

```
and everything works correctly.

**Comment by cavid90** [comment]
How to do it in vue 3 ?

**Comment by devbaji** [comment]
@cavid90 @Wasabiiiiiii @pine630 @pjkostrzewski @joseperu2503  
Sorry for the late reply guys, I can't replicate this issue on my side. I doubt this might be an error shown from [Google 3P Authorization JavaScript Library](https://developers.google.com/identity/oauth2/web/guides/load-3p-authorization-library), as this is just a wrapper around this library. I guess this might have fixed. Please reopen if this issue still exist.
