### ISSUE TITLE
Using the `use_fedcm_for_prompt` parameter

### ISSUE THREAD

**Issue by dauletbaev** [devbaji/vue3-google-login#44]
Google will make a regulation about 3rd party cookies at the end of the year. In order to adapt to this regulation within the scope of beta, it is necessary to use a parameter called "[use_fedcm_for_prompt](https://developers.google.com/identity/gsi/web/reference/js-reference?hl=en#use_fedcm_for_prompt)".

**Comment by devbaji** [comment]
@dauletbaev default value for use_fedcm_for_prompt is now set to true from version 2.0.21
