### ISSUE TITLE
3rd Party Cookie Deprecation Compliance?

### ISSUE THREAD

**Issue by auirarrazaval** [devbaji/vue3-google-login#45]
Hello!

I'm considering using this library for a new project I'm starting, but I'm a bit worried that the functionality might break when google [ drops 3rd Party Cookies](https://developers.google.com/identity/gsi/web/guides/supported-browsers?authuser=1#third-party_cookies) integrations in Q1 2024. 
Does this library account for this upcoming change?

Thanks!

**Comment by dauletbaev** [comment]
This package up to date check the https://github.com/devbaji/vue3-google-login/issues/44
