### ISSUE TITLE
Is version 2.0.24 missing dist folder

### ISSUE THREAD

**Issue by paulus-tungle** [devbaji/vue3-google-login#48]
<img width="258" alt="image" src="https://github.com/devbaji/vue3-google-login/assets/122441596/41dec950-0b9b-46aa-8a17-1ae799d14984">

I cannot see dist folder. Then I cannot build my project with 2.0.24. Tried with 2.0.23 and it works. Below is the error when I run npm install:
[91m[vite:resolve] Failed to resolve entry for package "vue3-google-login". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "vue3-google-login"

**Comment by devpate9** [comment]
Hi @paulus-tungle any way to resolve this?

**Comment by hungify2022** [comment]
Any update ...

**Comment by devpate9** [comment]
@hungify2022 pls downgrade the version to "vue3-google-login": "2.0.23"

**Comment by cvrppradeep** [comment]
you can use "vue3-google-login" dist folder is there

**Comment by paulus-tungle** [comment]
> @hungify2022 pls downgrade the version to "vue3-google-login": "2.0.23"

@devpate9 Yes I also have to fix version to 2.0.23 to make it work :D

**Comment by srijan-scanova** [comment]
Yes! Version 2.0.24 is missing with dist folder. Please version 2.0.23 contains the dist folder. PS: Make sure to change [`"vue3-google-login": "2.0.23"`] in your package.json file.

**Comment by devbaji** [comment]
@ranarn @cvrppradeep @srijan-scanova @paulus-tungle @devpate9 Sorry for the mistake, I have resolved this in version 2.0.25 please upgrade to the latest version.
