### ISSUE TITLE
SINGUP NEEDED

### ISSUE THREAD

**Issue by AteebNoOne** [devbaji/vue3-google-login#50]
It only gives Only give sign in prompt on googleTokenLogin and googleAuthCodeLogin. Want a prompt like context = 'signup' In these 2 functions aswell.

**Comment by devbaji** [comment]
Sorry this plugin is only intended to use Google's OAuth 2.0 to authenticate users. Once authenticated rest of the user session management logic must be done from your side.

**Comment by AteebNoOne** [comment]
> Sorry this plugin is only intended to use Google's OAuth 2.0 to authenticate users. Once authenticated rest of the user session management logic must be done from your side.

Okayy got it thank you, was confused about it
