### ISSUE TITLE
Cannot read properties of undefined (reading 'accounts')

### ISSUE THREAD

**Issue by Nomango** [devbaji/vue3-google-login#54]
Hi, there. I received some error reports after importing this package.
![image](https://github.com/devbaji/vue3-google-login/assets/22350366/7114b9c5-bb5d-4249-b48c-6a90dc409064)

It seems that this anomaly only occurs on mobile devices. (Chrome Mobile with Android 10 only)
![image](https://github.com/devbaji/vue3-google-login/assets/22350366/7aacce26-41df-4491-92aa-0f9bfc1f102b)

Possibly caused by this line.
https://github.com/devbaji/vue3-google-login/blob/5cd5853890abbe27ffcbabf3151742ba26acdbe2/src/plugin/utils.ts#L259

**Comment by devbaji** [comment]
@Nomango Does this issue still exists? Can you help me replicate this issue? I don't have access to real device with android 10, I tried android emulator Pixel 3 XL with Android 10, but login was working fine
![image](https://github.com/devbaji/vue3-google-login/assets/57234359/3d87eedf-f3f1-49e2-af59-08d7d0f57e8e)

**Comment by devbaji** [comment]
Please feel to reopen if this issue still exists
