### ISSUE TITLE
FedCM get() rejects with AbortError: signal is aborted without reason

### ISSUE THREAD

**Issue by NurTuam** [devbaji/vue3-google-login#56]
![image](https://github.com/devbaji/vue3-google-login/assets/44156411/f3a0c80b-8e80-4b8b-b2c6-396553e2846d)
How to fix this problem? When I call the googleOneTap function, and then I close the popup，it will happen.  It looks like the Google ApI will limit login status, need wait sometimes like ApI saying or clear browsing of data, the popup will only awaken it again，but more than users do not this operate. Can the component upGrade FedCM() to fix?

**Comment by NurTuam** [comment]
how to fix this problem

**Comment by yxichan** [comment]
good question

**Comment by SaidAlSouti** [comment]
Same issue here

**Comment by ginlink** [comment]
@NurTuam 

check this, make sure it is enabled

<img width="314" alt="image" src="https://github.com/devbaji/vue3-google-login/assets/35068110/2b2e27a6-d727-4b6c-baee-09336555ed3b">

**Comment by devbaji** [comment]
@SaidAlSouti  @NurTuam Sorry for the late reply, are you are referring to cooldown period? If the user closes the One Tap prompt manually, the One Tap prompt will be suppressed, see [here](https://developers.google.com/identity/gsi/web/guides/features#exponential_cooldown), I guess the error is from google library which I don't have any control of, as this NPM package is a wrapper over [Google 3P Authorization JavaScript Library](https://developers.google.com/identity/oauth2/web/guides/load-3p-authorization-library)
