### ISSUE TITLE
Plugin is working on dev branch but not demo branch

### ISSUE THREAD

**Issue by andreacuevas90** [devbaji/vue3-google-login#57]
I've added the plugin to my project and it is working perfectly on my dev branch but won't work on my demo branch. This seems strange to me as I've merged dev onto demo. 

The project is built using Vue 3 + Vite.

The error I get on the demo branch is 403 Forbidden. The Google Client ID I am using is the same for both.

**Comment by devbaji** [comment]
@andreacuevas90 Is the domain/url of apps running on both branch same?

**Comment by andreacuevas90** [comment]
Thank you for replying! I fixed it. The domain was slightly different. We ended up creating separate Client IDs.
