### ISSUE TITLE
When I successfully log in, I will be redirected to the dashboard page and the Google login pop-up in the upper right corner should not pop up again

### ISSUE THREAD

**Issue by yaowangmx** [devbaji/vue3-google-login#58]
The login page integrates email login and googleOneTap. After logging in with email, I will be redirected to the dashboard page, and then a Google login pop-up window will pop up in the upper right corner of the dashboard page. Is there a way to disable this after successful login。

![image](https://github.com/devbaji/vue3-google-login/assets/17875101/1a062b77-6f7c-4665-ae06-2cd8812478f7)

![image](https://github.com/devbaji/vue3-google-login/assets/17875101/e933016c-1e69-48a8-9161-ac6521385af8)

**Comment by devbaji** [comment]
@yaowangmx This have to be done from your end, inside your dashboard page/component you should not render the GoogleLogin component.
