### ISSUE TITLE
Can I use this with vuex? 

### ISSUE THREAD

**Issue by koromkorom** [devbaji/vue3-google-login#63]
Hi, 

is there a way to use this with `vuex`? 

I think it comes down to passing something to `userIsAuthenticated` parameter of `createStore`.

A minimal example would be amazing. 

Thank you!

**Comment by devbaji** [comment]
Hi @koromkorom this is just a wrapper plugin which only intended to add the google login button, rest of the logics, like setting if user logged in in vuex/pinia store must be done by your side once you catches a successful login inside the callback.
