### ISSUE TITLE
Vike SSR Example Suggestion

### ISSUE THREAD

**Issue by TimJohns** [devbaji/vue3-google-login#64]
Thanks for the work on this plug-in. I'm using it with the Vike framework, and would suggest an additional example in the docs at 
[No SSR support](https://devbaji.github.io/vue3-google-login/#no-ssr-support):

## Vike

In Vike applications, you can use the [clientOnly helper](https://vike.dev/clientOnly#vue), which is used for purposely rendering a component only on client side. 

```Vue
<template>
  <GoogleLogin :callback="googleLoginCallback" client-id="YOUR_GOOGLE_CLIENT_ID"/>
</template>

<script setup lang="ts">
import { clientOnly } from 'vike-vue/clientOnly'
const GoogleLogin = clientOnly(async () => (await import('vue3-google-login')).GoogleLogin);
</script>
```

**Comment by devbaji** [comment]
@TimJohns Thanks added to the docs
