### ISSUE TITLE
Bug: Missing `dist` folder in 2.0.32 npm build

### ISSUE THREAD

**Issue by escral** [devbaji/vue3-google-login#68]
https://www.npmjs.com/package/vue3-google-login/v/2.0.32?activeTab=code

**Comment by mertcelen** [comment]
I'm having same problem 👍🏻

**Comment by pojdrovic** [comment]
Same! Builds are breaking

**Comment by Firu115** [comment]
How does that even happen?!

**Comment by devbaji** [comment]
@escral @mertcelen @pojdrovic @Firu115 Sorry for the trouble guys, I was trying to automate the build process, silly me forgot to add npm run build to the YML file 😟
Fixed this in the latest version 2.0.33

**Comment by Firu115** [comment]
We forgive you!
